//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMVMU
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginalText
    {
        public int ID_OriginalTextCompose { get; set; }
        public int Stage { get; set; }
        public string TextCompose { get; set; }
        public int id_Kategory { get; set; }
        public Nullable<int> id_Prepodavatel { get; set; }
    
        public virtual Kategorii Kategorii { get; set; }
    }
}
