//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMVMU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepodavateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prepodavateli()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int ID_Prepodavatel { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateStop { get; set; }
        public Nullable<int> idLastStudentPlan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
