//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMVMU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Kompositors = new HashSet<Kompositors>();
        }
    
        public int ID_Student { get; set; }
        public string NameFile { get; set; }
        public string NameText { get; set; }
        public string StudGroup { get; set; }
        public int StudCourse { get; set; }
        public int id_Prepod { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public Nullable<int> LastKompos1 { get; set; }
        public Nullable<int> LastKompos2 { get; set; }
        public Nullable<int> LastKompos3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kompositors> Kompositors { get; set; }
        public virtual Prepodavateli Prepodavateli { get; set; }
    }
}
