//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMVMU.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composer
    {
        public int ID_Composer { get; set; }
        public string ComposerAndComposition { get; set; }
        public int id_Student { get; set; }
        public int id_Category { get; set; }
        public Nullable<int> LastStage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Student Student { get; set; }
    }
}
