//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMVMU.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kompositors
    {
        public int ID_Kompos { get; set; }
        public string KomposAndName { get; set; }
        public int id_Student { get; set; }
        public int id_Kat { get; set; }
        public Nullable<int> LastStage { get; set; }
    
        public virtual Kategorii Kategorii { get; set; }
        public virtual Students Students { get; set; }
    }
}
