//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMVMU.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginalText
    {
        public int ID_OriginalText { get; set; }
        public int Stage { get; set; }
        public string Text { get; set; }
        public int id_Category { get; set; }
        public Nullable<int> id_Teacher { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
